name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Nastavení cache pro Docker vrstvy
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Aktivace BuildKitu a build image s cache
      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache -t robotframework-test .

      - name: Run Robot Framework tests
        run: docker run -v ${{ github.workspace }}/results:/robotframework/results robotframework-test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: robot-framework-results
          path: results/
